name: azshop
description: A new Flutter application.

version: 5.0+50

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  introduction_screen: ^1.0.5+2
#  BSD licence:
  streaming_shared_preferences: ^1.0.1
  font_awesome_flutter: ^8.5.0
  carousel_slider: ^1.4.1
  provider: ^4.0.1
  logger: ^0.8.3 #testing logger on shake
  sensors: ^0.4.1+8
  share: ^0.6.3+6
#  rxdart: ^0.23.1

  #custom widget design
  flare_flutter: ^2.0.1
  flare_dart: ^2.2.5

  # Firebase dependencies
  firebase_core: ^0.4.0
  firebase_auth: ^0.14.0
  firebase_messaging: ^6.0.9
  cloud_firestore: ^0.12.9

#  google_sign_in: ^4.0.1 # Firebase auth dependency
#  firebase_crashlytics: ^0.1.0+2
#  firebase_analytics: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/cc.png
    - assets/on1.png
    - assets/on2.png
    - assets/on3.png
    - assets/food1.jpeg
    - assets/food2.jpeg
    - assets/food3.jpeg
    - assets/food4.jpeg
    - assets/food5.jpeg
    - assets/food6.jpeg
    - assets/food7.jpeg
    - assets/food8.jpeg
    - assets/food9.jpeg
    - assets/food10.jpeg
    - assets/food11.jpeg
    - assets/food12.jpg
    - assets/cm1.jpeg
    - assets/cm2.jpeg
    - assets/cm3.jpeg
    - assets/cm4.jpeg


